name: buildroot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build repo in spinarak docker container
      run: |
        docker run \
        -v ${{ github.workspace }}:/packages registry.gitlab.com/4tu/spinarak \
        /bin/bash -c "cd /packages && python3 /home/app/spinarak.py"
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: output
        path: public

    - name: Deploy via GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}